M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date So 11 Sep 2022 18:48:00 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-11T18:48:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X80.25Y-31.2
T0
M30
